name: 01 - Create Project From Template

on:
  workflow_dispatch:
    inputs:
      repository_org:
        required: true
        default: 'pknw1-www'
      repository_name:
        required: true
        default: 'webservice'
      repository_description:
        required: true
        default: 'description'
      repository_type:
        type: choice
        required: true
        default: 'new_development'
        options:
          - new_development
          - new_www_development
          - boilerplate_compose
          - external_repo_source
          - external_compose_source
      external_repo_source:
        default: ''
        required: false
      external_link:
        default: ''
        required: false
      external_compose_source:
        required: false
      create_private_config:
        type: boolean
        default: true
        required: true

jobs:
  summary:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ORG_TOKEN }}
      - name: summarise input variables
        run: |
          echo "## Summary of input variables" >> $GITHUB_SUMMARY


  create_repository:
    runs-on: ubuntu-latest
    needs: summary
    if: ${{ inputs.create_private_config == 'true' }}
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ORG_TOKEN }}
      - name: Creating GitHub Organization Repository
        uses: howlowck/create-repo-action@v1.0
        with:
          zipPath: 'deploy/zipFile.zip'
          repoOrg: '${{ inputs.repository_org }}'
          repoName: '${{ inputs.repository_name }}'
          repoDescription: '${{ inputs.repository_description }} - ${{ inputs.external_repo_source }} - ${{ inputs.external_link }}'
          repoVisibility: 'private'
          securityToken: ${{ secrets.GH_ORG_TOKEN }}
